### ISSUE TITLE
잘못된 입력에 대한 예외 처리

### ISSUE THREAD

**Issue by Yang-soeun** [Yang-soeun/wordle#2]
## Description
입력 받은 String이 올바른 word 형식이 확인하는 부분 구현

## To-do
- [ ] 4글자 단어인지 확인
- [ ] 대문자로 이루어진 단어인지 확인
- [ ] 영어로만 이루어진 단어인지 확인
